### ISSUE TITLE
KeyError: 'gnnLayer.sage1.lin_l.weight'

### ISSUE THREAD

**Issue by zza234s** [FedEgo/FedEgo#1]
尊敬的作者您好：近日我拜读了您们的论文，感觉受益颇多，也非常感谢您们愿意开源代码~
我在运行main.py文件的第275行执行遇到了如下错误，不知能否请您帮忙分析一下出问题的原因
![image](https://user-images.githubusercontent.com/52850465/192780176-49a93d83-9e35-4119-89f2-0f495c8efc73.png)

**Comment by taolinzhang** [comment]
你的torch版本可能比较新, strict=false不起作用. 我的是 1.9.1+cu111.

**Comment by zza234s** [comment]
感谢回复~
好的，我再研究下
